// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

[#spring-cloud-oci-core]
== Spring Cloud OCI Core

Spring Cloud OCI provides a Spring Boot starter to auto-configure the core components.

Maven coordinates, using <<getting-started.adoc#bill-of-materials, Spring Cloud OCI BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.oracle.cloud.spring</groupId>
    <artifactId>spring-cloud-oci-starter</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.oracle.cloud.spring:spring-cloud-oci-starter")
}
----

=== Configuration

The following options may be configured with Spring Cloud core.

|===========================================================================
| Name | Description | Required | Default value
| `spring.cloud.gcp.core.enabled` | Enables or disables GCP core auto configuration | No | `true`
|===========================================================================

=== Project ID

`GcpProjectIdProvider` is a functional interface that returns a GCP project ID string.

[source,java]
----
public interface GcpProjectIdProvider {
	String getProjectId();
}
----

The Spring Cloud GCP starter auto-configures a `GcpProjectIdProvider`.
If a `spring.cloud.gcp.project-id` property is specified, the provided `GcpProjectIdProvider` returns that property value.

[source,java]
----
spring.cloud.gcp.project-id=my-gcp-project-id
----

Otherwise, the project ID is discovered based on an
https://cloud.google.com/java/docs/reference/google-cloud-core/latest/com.google.cloud.ServiceOptions#com_google_cloud_ServiceOptions_getDefaultProjectId__[ordered list of rules]:

1. The project ID specified by the `GOOGLE_CLOUD_PROJECT` environment variable
2. The Google App Engine project ID
3. The project ID specified in the JSON credentials file pointed by the `GOOGLE_APPLICATION_CREDENTIALS` environment variable
4. The Google Cloud SDK project ID
5. The Google Compute Engine project ID, from the Google Compute Engine Metadata Server

=== Authentication Configuration

Spring Cloud OCI allows you to authenticate with OCI with various following available options.

==== Config File Based Authentication

By default config file based authentication is enabled. There are below optional configuration to choose custom config profile name and config file name.

----
spring.cloud.oci.config.profile = DEFAULT
spring.cloud.oci.config.file = <FILE_PATH>
----

==== Simple Authentication

Set the config.type to `SIMPLE` and set related required properties as below. All the below properties are mandatory.

----
spring.cloud.oci.config.type = SIMPLE
spring.cloud.oci.config.userId = <USER_ID>
spring.cloud.oci.config.tenantId = <TENANT_ID>
spring.cloud.oci.config.fingerprint = <FINGERPRINT>
spring.cloud.oci.config.privateKey = <PRIVATE_KEY_FILE_PATH>
spring.cloud.oci.config.passPhrase = <PASS_PHRASE>
----

==== Instance Principal Configuration

Set the config.type to `INSTANCE_PRINCIPAL` as below.

----
spring.cloud.oci.config.type = INSTANCE_PRINCIPAL
----

==== Resource Principal Configuration

Set the config.type to `RESOURCE_PRINCIPAL` as below.

----
spring.cloud.oci.config.type = RESOURCE_PRINCIPAL
----

=== Region Configuration

OCI services are available in different regions. Based on the custom requirements, the user can host the application on different OCI regions. The below configuration allows to set specific region for the entire application.

----
spring.cloud.oci.region.staticRegion = US_ASHBURN_1
----

=== Compartment Configuration

A compartment is a logical container, to organize and control access to the Oracle Cloud Infrastructure (OCI) Resources (Compute, Storage, Network, Load Balancer, etc) created within that compartmen. Below configuration allows you to set default compartment for your application.

----
spring.cloud.oci.compartment.staticCompartment = <COMPARTMENT_OCID>
----

=== Spring Initializr

This starter is available from https://start.spring.io/[Spring Initializr] through the `OCI Support` entry.
