# This workflow will build a Java project with Maven

name: Run the Integration Tests for Spring Cloud OCI

on:
  push:
    branches: [ main, topic_jjyoti_* ]
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Define the release version"
        required: true
        default: ""
      developmentVersion:
        description: "Define the snapshot version"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'maven'
      - name: Configure Git User
        run: |
          git config user.email "jeewan.jyoti@oracle.com"
          git config user.name "jjeewan"
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Run Maven Build and Test
        run: |
          mvn clean \
            -Pspring-cloud-oci-ci-it \
            -DuserId=${{ secrets.userId }} \
            -DtenantId=${{ secrets.tenantId }} \
            -Dfingerprint=${{ secrets.fingerprint }} \
            -Dregion=${{ env.region }} \
            -DprivateKeyContent=${{ secrets.privateKeyContent }} \
            -Dit.notification=${{ env.it_notification }} \
            -DtopicName=${{ env.topicName }} \
            -DcompartmentId=${{ secrets.compartmentId }} \
            -Dit.logging=${{ env.it_logging }} \
            -DlogId=${{ env.logId }} \
            install